// moviesData.js

const moviesByMood = {
  happy: [
    { title: "The Pursuit of Happyness", trailer: "https://www.youtube.com/embed/89Kq8SDyvfg" },
    { title: "Paddington", trailer: "https://www.youtube.com/embed/XWX1YJ4Fbw0" },
    { title: "Sing", trailer: "https://www.youtube.com/embed/jWD4ezh5z6s" },
    { title: "Mamma Mia!", trailer: "https://www.youtube.com/embed/ABgBg7XfWf4" },
    { title: "The Intern", trailer: "https://www.youtube.com/embed/ZU3Xban0Y6A" },
    { title: "Finding Nemo", trailer: "https://www.youtube.com/embed/wZdpNglLbt8" },
    { title: "Zootopia", trailer: "https://www.youtube.com/embed/jWM0ct-OLsM" },
    { title: "Coco", trailer: "https://www.youtube.com/embed/xlnPHQ3TLX8" },
    { title: "Up", trailer: "https://www.youtube.com/embed/ORFWdXl_zJ4" },
    { title: "Shrek", trailer: "https://www.youtube.com/embed/CwXOrWvPBPk" },
    { title: "The Princess Diaries", trailer: "https://www.youtube.com/embed/rGwi-vcdA5M" },
    { title: "La La Land", trailer: "https://www.youtube.com/embed/0pdqf4P9MB8" },
    { title: "Despicable Me", trailer: "https://www.youtube.com/embed/zzCZ1W_CUoI" },
    { title: "Tangled", trailer: "https://www.youtube.com/embed/ycoY201RTRo" },
    { title: "Sing 2", trailer: "https://www.youtube.com/embed/EPZu5MA2uqI" },
    { title: "Toy Story", trailer: "https://www.youtube.com/embed/v-PjgYDrg70" },
    { title: "Luca", trailer: "https://www.youtube.com/embed/mYfJxlgR2jw" },
    { title: "Inside Out", trailer: "https://www.youtube.com/embed/seMwpP0yeu4" },
    { title: "Big Hero 6", trailer: "https://www.youtube.com/embed/z3biFxZIJOQ" },
    { title: "Wreck-It Ralph", trailer: "https://www.youtube.com/embed/87E6N7ToCxs" },
  ],
  sad: [
    { title: "The Fault in Our Stars", trailer: "https://www.youtube.com/embed/9ItBvH5J6ss" },
    { title: "Bridge to Terabithia", trailer: "https://www.youtube.com/embed/8QvElYcb4k8" },
    { title: "Hachi: A Dog's Tale", trailer: "https://www.youtube.com/embed/SfLV8hD7zX4" },
    { title: "Marley & Me", trailer: "https://www.youtube.com/embed/VLLL5Gf_C8c" },
    { title: "The Green Mile", trailer: "https://www.youtube.com/embed/Ki4haFrqSrw" },
    { title: "Titanic", trailer: "https://www.youtube.com/embed/kVrqfYjkTdQ" },
    { title: "The Boy in the Striped Pajamas", trailer: "https://www.youtube.com/embed/pFxrN2niTFA" },
    { title: "The Lovely Bones", trailer: "https://www.youtube.com/embed/i76h9zG-wi4" },
    { title: "Room", trailer: "https://www.youtube.com/embed/E_Ci-pAL4eE" },
    { title: "Atonement", trailer: "https://www.youtube.com/embed/1vUUuxUV33k" },
    { title: "The Notebook", trailer: "https://www.youtube.com/embed/FsQ5pI4gOyo" },
    { title: "Lion", trailer: "https://www.youtube.com/embed/ziOLGzKq6oo" },
    { title: "Five Feet Apart", trailer: "https://www.youtube.com/embed/XtgCqMZofqM" },
    { title: "The Kite Runner", trailer: "https://www.youtube.com/embed/3p1-TYtG924" },
    { title: "The Pianist", trailer: "https://www.youtube.com/embed/BFwGqLa_oAo" },
    { title: "Me Before You", trailer: "https://www.youtube.com/embed/Eh993__rOxA" },
    { title: "My Sister's Keeper", trailer: "https://www.youtube.com/embed/EdZZLdjBfCI" },
    { title: "Still Alice", trailer: "https://www.youtube.com/embed/ZrXrZ5iiR0o" },
    { title: "Life is Beautiful", trailer: "https://www.youtube.com/embed/pAYEQP8gx3w" },
    { title: "The Blind Side", trailer: "https://www.youtube.com/embed/BXlZKBOk_Hw" },
  ],
  excited: [
    { title: "Mad Max: Fury Road", trailer: "https://www.youtube.com/embed/hEJnMQG9ev8" },
    { title: "Inception", trailer: "https://www.youtube.com/embed/YoHD9XEInc0" },
    { title: "Avengers: Endgame", trailer: "https://www.youtube.com/embed/TcMBFSGVi1c" },
    { title: "John Wick", trailer: "https://www.youtube.com/embed/2AUmvWm5ZDQ" },
    { title: "The Dark Knight", trailer: "https://www.youtube.com/embed/EXeTwQWrcwY" },
    { title: "Interstellar", trailer: "https://www.youtube.com/embed/zSWdZVtXT7E" },
    { title: "Guardians of the Galaxy", trailer: "https://www.youtube.com/embed/d96cjJhvlMA" },
    { title: "Iron Man", trailer: "https://www.youtube.com/embed/8ugaeA-nMTc" },
    { title: "The Matrix", trailer: "https://www.youtube.com/embed/vKQi3bBA1y8" },
    { title: "Jurassic World", trailer: "https://www.youtube.com/embed/RFinNxS5KN4" },
    { title: "Fast & Furious 7", trailer: "https://www.youtube.com/embed/Skpu5HaVkOc" },
    { title: "Top Gun: Maverick", trailer: "https://www.youtube.com/embed/giXco2jaZ_4" },
    { title: "Mission: Impossible – Fallout", trailer: "https://www.youtube.com/embed/wb49-oV0F78" },
    { title: "The Batman", trailer: "https://www.youtube.com/embed/mqqft2x_Aa4" },
    { title: "Dune", trailer: "https://www.youtube.com/embed/8g18jFHCLXk" },
    { title: "Ready Player One", trailer: "https://www.youtube.com/embed/cSp1dM2Vj48" },
    { title: "Edge of Tomorrow", trailer: "https://www.youtube.com/embed/yUmSVcttXnI" },
    { title: "The Hunger Games", trailer: "https://www.youtube.com/embed/mfmrPu43DF8" },
    { title: "Pacific Rim", trailer: "https://www.youtube.com/embed/5guMumPFBag" },
    { title: "The Equalizer", trailer: "https://www.youtube.com/embed/VjctHUEmutw" },
  ],
  angry: [
    { title: "Joker", trailer: "https://www.youtube.com/embed/zAGVQLHvwOY" },
    { title: "Gladiator", trailer: "https://www.youtube.com/embed/owK1qxDselE" },
    { title: "Whiplash", trailer: "https://www.youtube.com/embed/7d_jQycdQGo" },
    { title: "Law Abiding Citizen", trailer: "https://www.youtube.com/embed/LX6kVRsdXW4" },
    { title: "Prisoners", trailer: "https://www.youtube.com/embed/bpXfcTF6iVk" },
    { title: "Fight Club", trailer: "https://www.youtube.com/embed/qtRKdVHc-cE" },
    { title: "No Country for Old Men", trailer: "https://www.youtube.com/embed/38A__WT3-o0" },
    { title: "Oldboy", trailer: "https://www.youtube.com/embed/tFwqPzGwuDY" },
    { title: "American History X", trailer: "https://www.youtube.com/embed/XfQYHqsiN5g" },
    { title: "Training Day", trailer: "https://www.youtube.com/embed/DXPJqRtkDP0" },
    { title: "The Revenant", trailer: "https://www.youtube.com/embed/LoebZZ8K5N0" },
    { title: "Pulp Fiction", trailer: "https://www.youtube.com/embed/s7EdQ4FqbhY" },
    { title: "Kill Bill", trailer: "https://www.youtube.com/embed/7kSuas6mRpk" },
    { title: "The Hateful Eight", trailer: "https://www.youtube.com/embed/6_UI1GzaWv0" },
    { title: "The Departed", trailer: "https://www.youtube.com/embed/iojhqm0JTW4" },
    { title: "The Town", trailer: "https://www.youtube.com/embed/htqXL94Rza4" },
    { title: "Sin City", trailer: "https://www.youtube.com/embed/6iB21hsprAQ" },
    { title: "Heat", trailer: "https://www.youtube.com/embed/0xbBLJ1WGwQ" },
    { title: "Revenge", trailer: "https://www.youtube.com/embed/5Cb3ik6zP2I" },
    { title: "Wrath of Man", trailer: "https://www.youtube.com/embed/EFYEni2gsK0" },
  ],
  chill: [
    { title: "The Secret Life of Walter Mitty", trailer: "https://www.youtube.com/embed/qdV6epB9F_8" },
    { title: "Chef", trailer: "https://www.youtube.com/embed/UeF16P5Elys" },
    { title: "Before Sunrise", trailer: "https://www.youtube.com/embed/9v6X-Dytlko" },
    { title: "Midnight in Paris", trailer: "https://www.youtube.com/embed/FAfR8omt-CY" },
    { title: "The Hundred-Foot Journey", trailer: "https://www.youtube.com/embed/yEO1TWeM5JU" },
    { title: "Her", trailer: "https://www.youtube.com/embed/WzV6mXIOVl4" },
    { title: "Lost in Translation", trailer: "https://www.youtube.com/embed/W6iVPCRflQM" },
    { title: "Call Me by Your Name", trailer: "https://www.youtube.com/embed/Z9AYPxH5NTM" },
    { title: "Lady Bird", trailer: "https://www.youtube.com/embed/cNi_HC839Wo" },
    { title: "Into the Wild", trailer: "https://www.youtube.com/embed/g7ArZ7VD-QQ" },
    { title: "Brooklyn", trailer: "https://www.youtube.com/embed/15syDwC000k" },
    { title: "About Time", trailer: "https://www.youtube.com/embed/T7A810duHvw" },
    { title: "Moonlight", trailer: "https://www.youtube.com/embed/9NJj12tJzqc" },
    { title: "Adventureland", trailer: "https://www.youtube.com/embed/vsXE-FK4w2g" },
    { title: "Frances Ha", trailer: "https://www.youtube.com/embed/YBn5dgXFMis" },
    { title: "Big Fish", trailer: "https://www.youtube.com/embed/M3YVTgTl-F0" },
    { title: "Little Miss Sunshine", trailer: "https://www.youtube.com/embed/wvwVkllXT80" },
    { title: "The Grand Budapest Hotel", trailer: "https://www.youtube.com/embed/1Fg5iWmQjwk" },
    { title: "The Big Sick", trailer: "https://www.youtube.com/embed/PJmpSMRQhhs" },
    { title: "The Station Agent", trailer: "https://www.youtube.com/embed/VWzL3oL5fYs" },
  ]
};


module.exports = moviesByMood;


module.exports = moviesByMood;

module.exports = moviesByMood;

